//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntregaTress.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNOS()
        {
            this.ENVIOCODIGOQR = new HashSet<ENVIOCODIGOQR>();
        }
    
        public int cod_alumno { get; set; }
        public string rut_alumno { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido_alumno { get; set; }
        public string correo_alumno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVIOCODIGOQR> ENVIOCODIGOQR { get; set; }
    }
}
