//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntregaTress.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduVacEntities : DbContext
    {
        public EduVacEntities()
            : base("name=EduVacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<ENVIOCODIGOQR> ENVIOCODIGOQR { get; set; }
        public virtual DbSet<QRENTRADA> QRENTRADA { get; set; }
        public virtual DbSet<SALAS> SALAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
