//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntregaTress.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRENTRADA
    {
        public int cod_codigo2 { get; set; }
        public int fk_sala { get; set; }
        public int fk_qr { get; set; }
        public System.DateTime fecha_entrada { get; set; }
    
        public virtual ENVIOCODIGOQR ENVIOCODIGOQR { get; set; }
        public virtual SALAS SALAS { get; set; }
    }
}
