//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntregaTress.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int cod_usuario { get; set; }
        public string rut_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apellido_usuario { get; set; }
        public string correo_usuario { get; set; }
        public int usuario_admin { get; set; }
        public string pass_hash { get; set; }
        public string username { get; set; }
    }
}
